---
- name: set up ssh keygen
  shell: |
    mkdir /root/.ssh
    cp /vagrant/configuration/root/.ssh/id_rsa /root/.ssh/id_rsa
- name: install requirement packages
  yum:
    name: gcc, python36, python3-devel, mysql-devel, git
- name: install python packages
  pip:
    executable: pip3
    requirements: requirements.txt
    chdir: /vagrant
    state: forcereinstall
