# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'
  config.vm.provider "virtualbox" do |v|
    v.name = 'dev_project_name'
    v.cpus = '1'
    v.memory = '256'
  end

  config.vm.provision "shell", inline: "yum -y install epel-release"
  config.vm.provision "shell", inline: "yum -y install ansible"
  config.vm.provision "shell", inline: "ansible-playbook /vagrant/ansible/playbook.yml"
  config.vm.network "private_network", ip: '192.168.33.20'
end
